# Generated by Django 2.2.4 on 2020-05-10 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.Groups'),
        ),
    ]
