# Generated by Django 2.2.4 on 2020-05-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200510_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.IntegerField(blank=True, db_column='Member', null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='pool_count',
            field=models.IntegerField(blank=True, db_column='PoolCount', null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='rules',
            field=models.CharField(blank=True, db_column='Rules', max_length=400, null=True),
        ),
    ]
